version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5454:5454"
    volumes:
      - ./app/uploads:/app/uploads
      - ./app/data:/app/data
      - flashrank_cache:/app/.flashrank_cache
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OLLAMA_API_BASE=http://ollama:11434
      - DATABASE_URL=sqlite:///data/raglite.sqlite
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  ollama_data:
  flashrank_cache: